# Pin npm packages by running ./bin/importmap

pin "application", to: "application.js"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "flowbite", to: "flowbite/dist/flowbite.cjs.js"
pin "chart.js"
pin "dark_mode_controller", to: "controllers/dark_mode_controller.js"
pin "toast_controller", to: "controllers/toast_controller.js"
pin "modal_controller", to: "controllers/modal_controller.js"
pin "skeleton_controller", to: "controllers/skeleton_controller.js"
pin "@hotwired/stimulus", to: "stimulus@3.2.2"
pin "@hotwired/turbo", to: "turbo@8.0.12"
